### ISSUE TITLE
Quick overrider

### ISSUE THREAD

**Issue by dabo123148** [TBestLittleHelper/WarLightMods#1]
Multiplyer gets resetet every time you repoen the Settings menu cause you set 
Mod.Settings.Multiply = changeMultiply.GetIsChecked(); in Client_SaveConfigureUI.lua
but in Client_PresentConfigureUI.lua you request Mod.Settings.ChangeMultiply;

**Comment by TBestLittleHelper** [comment]
Whoops. I never noticed that, thanks for letting me know. Fixed it!
