### ISSUE TITLE
Attack/Transfer by Percentage

### ISSUE THREAD

**Issue by HinkyPanky** [TBestLittleHelper/WarLightMods#10]
When you attack or transfer by percentage 100% of your armies and that number is less than 100; then use the mod on the following turn, 100% is changed to 100 armies. Then on that turn, if your stack is greater than 100 armies, you have to redo the order if you want to transfer 100% again. 

Example with stacks and all territories worth 0:
Turn 1 deployments: Territory a: 312 armies, b: 59 c: 10
Turn 1 transfers (input orders myself): a transfers 100% (312 armies) to b, b transfers 100% (59 armies) to c.
Turn 2 deployments: a: 312, b:312, c:69
Turn 2 transfers (input orders using mod): a transfers 312 armies to b, b transfers only 100 armies to c and 212 armies are left in territory b.
Turn 3 deployments: a: 312, b: 524, c: 169.

Is it possible for the mod to recognise and use percentages? That would make it easier to use. If not, it is still very helpful and easy to use, so thank you for making it :)

**Comment by TBestLittleHelper** [comment]
relevant part : 

https://github.com/TBestLittleHelper/WarLightMods/blob/854f13067d4204815ac04c24d06f0270812a1010/TBest_Mods/LocalDeploymentFixer/Client_PresentMenuUI.lua#L145

https://www.warzone.com/wiki/Mod_API_Reference:GameOrderAttackTransfer

I recall trying to support % when I made the mod. But I don't remember why it was not part of the final mod. I will give it another look
