### ISSUE TITLE
Auto distribution can't be turned off

### ISSUE THREAD

**Issue by dabo123148** [TBestLittleHelper/WarLightMods#2]
Since you can't disable autodistribution, I suggest you change your description of the lotto mod to a way, in which auto distribution isn't mentioned any longer.

**Comment by TBestLittleHelper** [comment]
Hm. It appeared to work in SP, just fine. Turns picks to autodist, no problem there. 
EDIT:
I also see it working in MP for me. Just tested again

Do you have still have the issue?

**Comment by dabo123148** [comment]
What I mean is, that it's still written in the description.
Edit: You forgot to reload the code, on GitHub is a new description

**Comment by TBestLittleHelper** [comment]
Well, I just reloaded the code. I could have sworn I did it before, but I must have forgotten.

Thanks for letting me know!
